on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
                 
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: testgit.azurecr.io
            username: testgit
            password: dyA8P9tmxnNv+Kh7Vv6RFHH6kREMrh1Y
        - run: |
            docker build . -t testgit.azurecr.io/test:${{ github.sha }}
            docker push testgit.azurecr.io/test:${{ github.sha }}

